### ISSUE TITLE
docker run failed with "can't start new thread"

### ISSUE THREAD

**Issue by radeknoone** [8go/matrix-commander#80] opened 2022-06-16 20:53 UTC
```
[root@cnt2 md_matrix-commander]# mkdir -p /root/data/store
[root@cnt2 md_matrix-commander]# docker run --rm -ti -v /root/data:/data:z matrixcommander/matrix-commander
Credentials file "/data/credentials.json" was not found. There are 2
    possibilities for this.
1) This is your first time use? Setting up new credentials? Then welcome to
    matrix-commander. Continue, and in the next step you will be asked for
    homeserver, user, password and room id to create a credentials file.
2) You specified the credentials location incorrectly or you started matrix-
    commander from the wrong directory. Abort, change you directory if needed
    or set the credentials option correctly. Then start matrix-commander again.
Continue to create new credentials? (Yes or Ctrl-C to abort) Yes
Enter URL of your homeserver: [https://matrix.example.org] https://matrix.org
2022-06-16 20:52:24,933:    ERROR: matrix-commander: The program matrix-commander.py failed. Sorry.
2022-06-16 20:52:24,934:    ERROR: matrix-commander: can't start new thread
2022-06-16 20:52:24,934:     INFO: matrix-commander: 2 errors and 0 warnings occurred.

**Comment by radeknoone** [comment] 2022-06-16 20:56
```
With debug flag:

[root@cnt2 md_matrix-commander]# docker run --rm -ti -v /root/data:/data:z matrixcommander/matrix-commander -d
2022-06-16 20:54:46,023:    DEBUG: matrix-commander: Debug is turned on. debug count=1
2022-06-16 20:54:46,024:    DEBUG: matrix-commander: Separator is set to "    " of length 4. E.g. Col1    Col2.
2022-06-16 20:54:46,024:    DEBUG: matrix-commander: Encryption is always enabled. It cannot be turned off.
2022-06-16 20:54:46,024:    DEBUG: matrix-commander: All arguments are valid. All checks passed.
2022-06-16 20:54:46,024:    DEBUG: matrix-commander: Create directory /root/.run for PID file.
2022-06-16 20:54:46,024:    DEBUG: matrix-commander: Trying to create a PID file to store process id 1.
2022-06-16 20:54:46,025:    DEBUG: matrix-commander: Successfully created PID file "/root/.run/matrix-commander.a7e82a11-e762-437b-8efb-bd7a4c1baf3a.pid" to store process id 1.
2022-06-16 20:54:46,025:    DEBUG: matrix-commander: Stdin pipe is assigned to "none".
2022-06-16 20:54:46,025:    DEBUG: matrix-commander: SSL will be used. Default SSL certificate validation will be done for this connection.
2022-06-16 20:54:46,026:    DEBUG: matrix-commander: Credentials file was specified with full path. So we suggest that one. file: /data/credentials.json
2022-06-16 20:54:46,026:    DEBUG: matrix-commander: Found an existing store in directory "/data/store" (local or arguments). It will be used.
2022-06-16 20:54:46,026:    DEBUG: matrix-commander: Credentials file does not exist.
Credentials file "/data/credentials.json" was not found. There are 2
    possibilities for this.
1) This is your first time use? Setting up new credentials? Then welcome to
    matrix-commander. Continue, and in the next step you will be asked for
    homeserver, user, password and room id to create a credentials file.
2) You specified the credentials location incorrectly or you started matrix-
    commander from the wrong directory. Abort, change you directory if needed
    or set the credentials option correctly. Then start matrix-commander again.
Continue to create new credentials? (Yes or Ctrl-C to abort) Yes
Enter URL of your homeserver: [https://matrix.example.org] https://matrix.org
2022-06-16 20:54:56,219:    ERROR: matrix-commander: The program matrix-commander.py failed. Sorry.
2022-06-16 20:54:56,219:    DEBUG: matrix-commander: Cleanup: cleaning up.
2022-06-16 20:54:56,225:    ERROR: matrix-commander: can't start new thread
Here is the traceback.
Traceback (most recent call last):
  File "/usr/lib64/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/app/matrix_commander/matrix_commander.py", line 5264, in main_send
    await create_credentials_file(credentials_file, store_dir)
  File "/app/matrix_commander/matrix_commander.py", line 3577, in create_credentials_file
    async with session.get(
  File "/usr/local/lib64/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib64/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib64/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib64/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib64/python3.10/site-packages/aiohttp/connector.py", line 1154, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/lib64/python3.10/site-packages/aiohttp/connector.py", line 880, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib64/python3.10/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/lib64/python3.10/asyncio/base_events.py", line 860, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib64/python3.10/asyncio/base_events.py", line 818, in run_in_executor
    executor.submit(func, *args), loop=self)
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 176, in submit
    self._adjust_thread_count()
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 199, in _adjust_thread_count
    t.start()
  File "/usr/lib64/python3.10/threading.py", line 928, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/matrix_commander/matrix_commander.py", line 6987, in main
    main_inner(argv)
  File "/app/matrix_commander/matrix_commander.py", line 6937, in main_inner
    asyncio.run(main_send())
  File "/usr/lib64/python3.10/asyncio/runners.py", line 49, in run
    loop.run_until_complete(loop.shutdown_default_executor())
  File "/usr/lib64/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/lib64/python3.10/asyncio/base_events.py", line 567, in shutdown_default_executor
    thread.start()
  File "/usr/lib64/python3.10/threading.py", line 928, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

2022-06-16 20:54:56,225:     INFO: matrix-commander: 2 errors and 0 warnings occurred.

**Comment by radeknoone** [comment] 2022-06-16 20:57
Hi! I'm trying to run matrix-commander with docker run command, but there is always error as shown in logs. Is there any way how to get matrix-commander working?

**Comment by 8go** [comment] 2022-06-17 18:29
@radeknoone @xurizaemon 

try `--no-sso` 

Documentation says:
```
When using Docker, it is recommended to use the --no-sso flag because there is no browser available to perform web-based Single Sign-On.
```

**Comment by xurizaemon** [comment] 2022-06-17 19:22
I was seeing this behaviour when using `--no-sso`. The docs I was referring to were:

I referred to these docs:

- [README](https://github.com/8go/matrix-commander) refers to `docker pull matrixcommander/matrix-commander` which is where I got the image name
- [docker/README](https://github.com/8go/matrix-commander/tree/master/docker#using-the-image) instructs `docker run --rm -ti -v /my/chosen/folder:/data:z matrix-commander --no-ssl` (disabling SSL encryption, not SSO)
- https://github.com/8go/matrix-commander/issues/70#issuecomment-1146262658 mentions the `--no-sso` flag - I was including it in my testing, but I'm not certain if I got it from there or somewhere else 😖 

Here's what I see:

```
$ xurizaemon@bionic:/tmp/mxco$ docker run --rm -ti -v /tmp/mxco/data:/data:z matrixcommander/matrix-commander --no-sso
Credentials file "/data/credentials.json" was not found. There are 2
    possibilities for this.
1) This is your first time use? Setting up new credentials? Then welcome to
    matrix-commander. Continue, and in the next step you will be asked for
    homeserver, user, password and room id to create a credentials file.
2) You specified the credentials location incorrectly or you started matrix-
    commander from the wrong directory. Abort, change you directory if needed
    or set the credentials option correctly. Then start matrix-commander again.
Continue to create new credentials? (Yes or Ctrl-C to abort) Yes
Enter URL of your homeserver: [https://matrix.example.org] https://matrix.org
2022-06-17 19:15:32,298:    ERROR: matrix-commander: The program matrix-commander.py failed. Sorry.
2022-06-17 19:15:32,299:    ERROR: matrix-commander: can't start new thread
2022-06-17 19:15:32,299:     INFO: matrix-commander: 2 errors and 0 warnings occurred.
```

**Comment by xurizaemon** [comment] 2022-06-17 19:28
OK, I tested on a second laptop and found it worked. I suspect this might be related to Docker version. The test above is on my work system (Ubuntu Bionic) which I am a heavy daily user of Docker on, `Docker version 20.10.7, build f0df350`.

**Comment by 8go** [comment] 2022-06-17 22:34
Thank you @xurizaemon for your input and your tests. It is appreciated.

It seems to depend on the Ubuntu version? Which Python version on the Ubuntu Bionic system?

The exception is raised in `aiohttp`. Not sure what `matrix-commander` can do about that.

**Comment by xurizaemon** [comment] 2022-06-18 21:39
This is an interesting one! I do suspect it's related to the older Ubuntu release(s) combined with the Fedora base image here which may be relatively newer.

On the system which was demonstrating this bug, I launched the container (to reproduce the execution environment) and mounted in the app sourcecode (so I could modify and debug the code).

```
docker run -ti --entrypoint bash -v ~/Projects/src/matrix-commander:/app:z matrixcommander/matrix-commander
```

This gives me a bash shell inside Docker. First attempt to run current master in the Docker image fails due to missing `xdg`, which I fix using `pip`. This isn't the issue at hand.

```
[root@7d777a0b4e1b matrix_commander]# ./matrix-commander --no-sso
Traceback (most recent call last):
  File "/app/matrix_commander/./matrix-commander", line 5, in <module>
    from matrix_commander import main
  File "/app/matrix_commander/matrix_commander.py", line 1478, in <module>
    from xdg import xdg_config_home, xdg_data_home
ModuleNotFoundError: No module named 'xdg'

[root@7d777a0b4e1b matrix_commander]# pip3 install xdg
Collecting xdg
  Downloading xdg-5.1.1-py3-none-any.whl (5.0 kB)
Installing collected packages: xdg
Successfully installed xdg-5.1.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```

OK, let's see if we can reproduce the bug now, with a view to debugging it.

```
[root@7d777a0b4e1b matrix_commander]# ./matrix-commander --no-sso
Could not find an existing store directory anywhere.
There are 2 possibilities:
1) This is the first time you use matrix-commander or you want to create a new
    store. In this first case just continue, and a new store will be created.
    It will need to be verified. The store directory will be created in the
    directory "store". Optionally, consider moving the persistant storage
    directory files inside "store" into the directory
    "/root/.local/share/matrix-commander/store" for a more consistent
    experience.
2) You specified the store location incorrectly or you started matrix-commander
    from the wrong directory. In this second case abort, change you directory
    if needed or set the store option correctly. Then start matrix-commander
    again.
Credentials file "credentials.json" was not found. There are 2 possibilities
    for this.
1) This is your first time use? Setting up new credentials? Then welcome to
    matrix-commander. Continue, and in the next step you will be asked for
    homeserver, user, password and room id to create a credentials file.
2) You specified the credentials location incorrectly or you started matrix-
    commander from the wrong directory. Abort, change you directory if needed
    or set the credentials option correctly. Then start matrix-commander again.
Continue to create new credentials? (Yes or Ctrl-C to abort) Yes
Enter URL of your homeserver: [https://matrix.example.org] https://matrix.org
2022-06-18 21:14:23,339:    ERROR: matrix-commander: The program matrix-commander.py failed. Sorry.
2022-06-18 21:14:23,339:    ERROR: matrix-commander: can't start new thread
2022-06-18 21:14:23,339:     INFO: matrix-commander: 2 errors and 0 warnings occurred.
```

Cool,  bug reproduces, so we can debug it!

I wanted to install `strace` to look at this, as an alternative to activating debugging in `aiohttp`. I read the Dockerfile and established that this is Fedora and I need to use `dnf`.

```
[root@7d777a0b4e1b matrix_commander]# dnf install strace
Fedora 35 - x86_64                                                                    0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'fedora':
  - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64 [getaddrinfo() thread failed to start]
Error: Failed to download metadata for repo 'fedora': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64 [getaddrinfo() thread failed to start]
[root@7d777a0b4e1b matrix_commander]# dnf update
Fedora 35 - x86_64                                                                    0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'fedora':
  - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64 [getaddrinfo() thread failed to start]
Error: Failed to download metadata for repo 'fedora': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64 [getaddrinfo() thread failed to start]
```

Wait! That looks a lot like the same underlying error, doesn't it?

>  ERROR: matrix-commander: can't start new thread

> [getaddrinfo() thread failed to start]

A bit of searching for the second error message combined with "fedora 35" leads me to [ubuntu:21.10 and fedora:35 do not work on Docker 20.10.9](https://medium.com/nttlabs/ubuntu-21-10-and-fedora-35-do-not-work-on-docker-20-10-9-1cd439d9921). This post suggests that upgrading to Docker 20.10.10 or beyond should solve the problem.

Sure enough, the affected systems I see locally are below that version, and the unaffected systems are above it. I follow the installation instructions for my platform via https://docs.docker.com/engine/install/ which upgrades me from 20.10.7 to 20.10.17. (TIL my Docker install wasn't up to date!)

Now, let's test it again!

```
[root@bcbddbd075d1 matrix_commander]# ./matrix-commander --no-sso
Could not find an existing store directory anywhere.
There are 2 possibilities:
1) This is the first time you use matrix-commander or you want to create a new
    store. In this first case just continue, and a new store will be created.
    It will need to be verified. The store directory will be created in the
    directory "store". Optionally, consider moving the persistant storage
    directory files inside "store" into the directory
    "/root/.local/share/matrix-commander/store" for a more consistent
    experience.
2) You specified the store location incorrectly or you started matrix-commander
    from the wrong directory. In this second case abort, change you directory
    if needed or set the store option correctly. Then start matrix-commander
    again.
Credentials file "credentials.json" was not found. There are 2 possibilities
    for this.
1) This is your first time use? Setting up new credentials? Then welcome to
    matrix-commander. Continue, and in the next step you will be asked for
    homeserver, user, password and room id to create a credentials file.
2) You specified the credentials location incorrectly or you started matrix-
    commander from the wrong directory. Abort, change you directory if needed
    or set the credentials option correctly. Then start matrix-commander again.
Continue to create new credentials? (Yes or Ctrl-C to abort) yes
Enter URL of your homeserver: [https://matrix.example.org] https://matrix.org
Enter your full user ID: [@user:example.org] @examplebot:matrix.org
Choose a name for this device: [matrix-commander] 
Enter your room ID: [!SomeRoomIdString:example.org] !ewOgZEUrOZAAaQJNBv:matrix.org
2022-06-18 21:34:31,218:     INFO: matrix-commander: The persistent storage directory store was created for you.
Password: 
2022-06-18 21:34:37,301:     INFO: matrix-commander: Log in using a password was successful. Credentials were stored in file
"credentials.json". Run program "matrix-commander.py" again to login with
credentials and to send a message. If you plan on having many credential files,
consider moving them to directory "/root/.config/matrix-commander".

[root@bcbddbd075d1 matrix_commander]# ./matrix-commander --no-sso -m "hello world"
2022-06-18 21:34:51,130:     INFO: matrix-commander: This message was sent: "hello world" to room "!ewOgZEUrOZAAaQJNBv:matrix.org" as event "$165558809051479lvsSN:matrix.org".
```

Success!

The recommended solution if you hit this issue is to **upgrade your local Docker version to greater than 20.10.10**. More details about the cause are in [this post](https://medium.com/nttlabs/ubuntu-21-10-and-fedora-35-do-not-work-on-docker-20-10-9-1cd439d9921).

I believe this issue can be closed. @radeknoone perhaps you can confirm this solution works for you?

**Comment by 8go** [comment] 2022-06-19 15:50
Thank you @xurizaemon for debugging this. It seems like a version problem, but with many moving parts it was hard to find out the version of *WHAT* causes the problem. Thanks for dedicating time and for finding the solution @xurizaemon 

Footnote, has nothing to do with this `can't create thread` problem: `xdg` was added in v2.27.2 based on Issue #78. In version v2.37.5 I switched from PyPi package `xdg` to `pyxdg`. See `requirements.txt`.

**Comment by 8go** [comment] 2022-07-29 15:20
Closing this now.

Please re-open if need be.

**Closed by 8go** 2022-07-29 15:21 UTC
Labels: bug, solved

**Comment by 8go** [comment] 2023-05-24 16:24
As pointed out by @Benjamin-Loison in Issue #136 136  the usage of `--no-sso` is no longer correct.

The software has been changed in the past and the correct usage is now `matrix-commander --login password`.

So, instead of saying "don't use SSO" you must now say "I want to log in and authenticate with a password."
