### ISSUE TITLE
Feature Request: Send direct message (DM) without a prior room name

### ISSUE THREAD

**Issue by toushin-taishi** [8go/matrix-commander#56] opened 2021-12-02 05:30 UTC
Hello. Is it possible for matrix-commander to send DMs (direct message) to a matrix account without a prior room name?
I am thinking of using matrix-commander as a notification medium but cannot entirely automate the process if a room name is needed on every DM.

Kind regards

**Comment by edwinsage** [comment] 2022-04-25 00:10
I'm looking for this feature too.  The matrix-nio library supports creating rooms without aliases, and also direct messaging rooms, but it doesn't look like it's implemented in m-c.  I'm interested in adding support myself, but it will take a while as my Python is pretty shabby.  I'm a Perl guy ;)

**Comment by edwinsage** [comment] 2022-05-26 21:58
This is another subject where I have made a personal patch on my fork.  I assume the original issue is about needing to specify an alias when making a room, which can get in the way of generating rooms on the fly.

In my use case, users would "register" in one public room, and my bot would create and invite them to a private room to communicate directly.  While I could have invented a system for generating room aliases randomly and then included checks for when room alias collisions happen, I found it simpler to modify MC to allow it to make rooms that do not have an alias, and changed it to output the room ID whenever it creates a room.  It turns out the nio library already supports this and only requires making the room creation request without being given an alias, so the code change is minimal.  I didn't make a pull request again as it didn't seem like a neat solution, but the changes worked for my needs.  The two commits are here:
https://github.com/edwinsage/matrix-commander/commit/db7c278bd015f910b17a9b2cd9628efdaea844ab
https://github.com/edwinsage/matrix-commander/commit/8509f2b64be5a43f5876a0649a423032010573c1

This increases the risk of creating rooms that get "lost" as the only way to identify the room is on the output, rather than in your input, but presumably there is a way to list all rooms one is connected to (otherwise how would interactive matrix clients even work?).

**Comment by toushin-taishi** [comment] 2022-05-27 01:53
> Question: In the Element client (say on Android, or Webpage), can one send a DM, i.e. a message to someone, without a room name? As far as I can tell Element always has a room name, even for what they call "People" in their GUI.

Hi @8go.
In Element, one can use the command /msg <user-id> [<message>].
Element will automatically create a room if one does not exist between you and the <user-id>.

This was actually the inspiration for this feature request I guess.

**Comment by edwinsage** [comment] 2022-05-28 19:05
I've been trying to dig in to how this would work, but I'm still stuck at the moment.  It looks like there may be a way to get a list of potential DM rooms by user:
https://spec.matrix.org/v1.2/client-server-api/#mdirect
But I'm not sure how that interface works or how the information is updated, as it appears to be stored in user data, not in the room itself?  Maybe someone with more experience with the spec can make better sense of this.

**Comment by 8go** [comment] 2022-05-31 09:02
Apps with phone numbers like Signal and WhatsApp and Twitter support "DM" because there is makes sense. There is only one "you". These apps are person-based. You have exactly 1 account. (Generally speaking,)

Matrix is more "room"-based. Every person can have multiple "personas", so it is not so clear cut. 

@toushin-taishi : Ok, that was useful input. Thank you. That sort of confirms one possibility. (As mentioned) One could go though all the rooms to see if a room exists with only this one other recipient. If one or more of such rooms exist, send to an arbitrary one. If no such room exists, send an invite to create room. Etc.

@edwinsage : Thanks for the link. It adds a bit of information. It also confirms that the "is_direct" flag is more of a hint, it does not enforce anything. It expresses a desire. This was my understanding and continues to be my understanding. But from that URL https://spec.matrix.org/v1.2/client-server-api/#mdirect I learned that at the Synapse level there should be an API call to request from the server the list of all rooms that are labelled "is_direct". I will have a look at `matrix-nio` to see if there is such an API call also in `matrix-nio`.

**Comment by 8go** [comment] 2022-05-31 09:34
# Searches 

I did a search of "direct" in `matrix-nio` documentation:
https://matrix-nio.readthedocs.io/en/latest/search.html?q=direct&check_keywords=yes&area=default

Please correct me if I am wrong somewhere.  I found only 2 slightly relevant hits of the term "direct".

1)

https://matrix-nio.readthedocs.io/en/latest/nio.html?highlight=direct#module-nio.event_builders.direct_messages :: this is not appropriate, it allows sending to a specific device, but one must have the device ID, I don't think this is what a DM should do, a DM should send to all devices

2)

https://matrix-nio.readthedocs.io/en/latest/examples.html?highlight=direct#manual-encryption-key-verification :: Big portions  of this page are PRs from myself to matrix-nio. Just an irrelevant mention of `This can be a direct message or room; Matrix treats them the same`. 

Then I searched: https://matrix-nio.readthedocs.io/en/latest/search.html?q=is_direct&check_keywords=yes&area=default#

I found what I expected: how to set the `is_direct` flag as a hint when you create a room. Nothing beyond that. 

# Conclusion

I reached the conclusion that `matrix-nio` does not have any API that would support anything related to "DM". Again, I would love for someone to tell me that I am wrong and that the API call is XYZ. So, if someone out there knows how to do a "DM" call in `matrix-nio` please do tell us. 

That only leaves me with the idea of getting all rooms, all members of all these rooms to try to find a room that only has sender and receiver in it and nobody else. Take that room id and send the message there. Worth it? Please comment.

**Comment by 8go** [comment] 2022-05-31 17:31
@edwinsage and @toushin-taishi 

Finally I implemented 2 membership options for rooms and room members. 

Have a look at commit [acb4bde](https://github.com/8go/matrix-commander/commit/acb4bde0a8d00bb3396f4f765a8c35714e12f37e)

```
  --joined-rooms        Print the list of joined rooms. All rooms that you are
                        a member of will be printed, one room per line.
  --joined-members JOINED_MEMBERS [JOINED_MEMBERS ...]
                        Print the list of joined members for one or multiple
                        rooms. If you want to print the joined members of all
                        rooms that you are member of, then use the special
                        character '*'.
```

That gets us much closer to a DM.

**Comment by edwinsage** [comment] 2022-05-31 18:29
> That only leaves me with the idea of getting all rooms, all members of all these rooms to try to find a room that only has sender and receiver in it and nobody else. Take that room id and send the message there. Worth it? Please comment.

I think if matrix-nio has a way to check whether the `is_direct` flag is set for a room, then it would make sense to add a polling feature to allow MC to find and use DM rooms.  If not, then I think it makes more sense to leave this to a wrapper or other script (outside of this project) that creates its own DM rooms and tracks their existence itself.  In that case, it would be helpful to add a feature that allows creating rooms with the `is_direct` flag to MC.

**Comment by 8go** [comment] 2022-05-31 19:33
https://matrix-nio.readthedocs.io/en/latest/nio.html?module-nio.rooms#module-nio.rooms

There is no API call to get `is_direct` flag. 

But there is an API call for `is_group`
https://matrix-nio.readthedocs.io/en/latest/nio.html?nio.rooms.MatrixRoom.is_group

It says: "Determine whether a room is an ad-hoc group (often a direct chat). A group is an unnamed room with no canonical alias." 

Again, this is just a hint. No guarantee that this is actually a room between 2 people.

**Comment by 8go** [comment] 2022-06-01 09:33
DM is now done. See commit [40e3c87](https://github.com/8go/matrix-commander/commit/40e3c871810b08ee738d62dd54e77f772aa435ad)

It gets the rooms of the sender, then it gets the members of all these rooms, then it searches through this list to find a room that only has 2 members and them being sender and receiver. As name match 3 choices are handled: full user id, partial user id, display name. 

Try it and report back if it works for you!

- one can now specify a person (instead of a room to send to)
- --message, --audio, etc. now work in conjunction with --user
- --listen (some forms) now work in conjunction with --user

```
$ # Send to a specific user, DM, direct messaging, using full user id
$ matrix-commander -m "hi" --user 'https://github.com/myfriend:example.org'
$ # Send to a specific user, DM, direct messaging, using partial user id
$ # It will be assumed that user https://github.com/myfriend is on same homeserver
$ matrix-commander -m "hi" --user 'https://github.com/myfriend'
$ # Send to a specific user, DM, direct messaging, using display name
$ # Careful! Display names might not be unique. Don't DM the wrong person!
$ # To double-check the display names do a --joined-members "*"
$ matrix-commander -m "hi" -u 'Joe'
$ # Send to multiple users
$ matrix-commander -m "hi" -u '@joe:example.org' 'https://github.com/jane:example.org'
$ # Send to multiple users, another way
$ matrix-commander -m "hi" -u '@joe:example.org' -u 'https://github.com/jane:example.org'
```

**Comment by toushin-taishi** [comment] 2022-06-07 01:45
Hi @8go,
Thanks for the effort in implementing this request.
I tested using the latest git and as the commit stated, it works if the bot and the recipient have an existing room.

Please tell me if i can be of any help in terms of testing this new feature.

**Comment by 8go** [comment] 2022-06-07 16:33
Thanks @toushin-taishi for the feedback, confirming that it is working for you. Great to hear.

My intention was to leave it as-is. The user is responsible for creating the room and sending invite through any means he wants, e.g. with Element or with `matrix-commander --room-create ... ` and `matrix-commander --room-invite ... ` . 

I just saw that GitHub automatically replaced `@user` patterns in my copy-paste of the code. The above examples look weird, now fixed.

**Comment by TroyWilson1** [comment] 2022-09-15 22:18
DM messages only get set to a room and not to users outside room

`matrix-commander -m "hi" --user '@bob'
INFO: matrix-commander: No rooms are given. This should not happen. Maybe your DM rooms specified via --user were not found. This text message is being dropped and NOT sent.
`

**Comment by 8go** [comment] 2022-10-02 15:13
@TroyWilson1 Please explain yourself by adding more detail. I am not sure what the issue is. The room will not be automatically created. You have to do that separately.

**Comment by 8go** [comment] 2022-10-03 20:44
Closing issue. Reopen if need be.

**Closed by 8go** 2022-10-03 20:44 UTC
Labels: enhancement, solved
